// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "5a3b8404-3ee7-447f-bfdd-c213c4cdd7bc";

char SSID[50];                               // = SECRET_SSID;                   // Network SSID (name)
char PASS[50];                               // = SECRET_PASS;             // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY; // Secret device password

int cntForCloud;

void initProperties()
{
  char Buf[50];
  String SSIDasString;
  SSIDasString = WiFi.SSID();
  SSIDasString.toCharArray(Buf, 50);
  strcpy(SSID, Buf);

  String PASSWORDasString;
  PASSWORDasString = WiFi.psk();
  PASSWORDasString.toCharArray(Buf, 50);
  strcpy(PASS, Buf);

  // SSID = WiFi.SSID();

  // SSID = SSIDasString //.toCharArray(Buf, 50);

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cntForCloud, READ, 5 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
